//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEmpleado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CerveceriaEntities : DbContext
    {
        public CerveceriaEntities()
            : base("name=CerveceriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Empleado> TB_Empleado { get; set; }
        public virtual DbSet<TB_Producto> TB_Producto { get; set; }
        public virtual DbSet<TB_Proveedor> TB_Proveedor { get; set; }
    
        public virtual int usp_ActualizarEmpleado(string vcodEmpl, string idUbig, string nombEmpl, string apeEmpl, string telfEmpl, string emailEmpl, Nullable<System.DateTime> fVencContEmpl, string sexoEmpl, string dniEmpl, string usuRegEmpl, string estEmpl, string aCF)
        {
            var vcodEmplParameter = vcodEmpl != null ?
                new ObjectParameter("vcodEmpl", vcodEmpl) :
                new ObjectParameter("vcodEmpl", typeof(string));
    
            var idUbigParameter = idUbig != null ?
                new ObjectParameter("idUbig", idUbig) :
                new ObjectParameter("idUbig", typeof(string));
    
            var nombEmplParameter = nombEmpl != null ?
                new ObjectParameter("NombEmpl", nombEmpl) :
                new ObjectParameter("NombEmpl", typeof(string));
    
            var apeEmplParameter = apeEmpl != null ?
                new ObjectParameter("ApeEmpl", apeEmpl) :
                new ObjectParameter("ApeEmpl", typeof(string));
    
            var telfEmplParameter = telfEmpl != null ?
                new ObjectParameter("telfEmpl", telfEmpl) :
                new ObjectParameter("telfEmpl", typeof(string));
    
            var emailEmplParameter = emailEmpl != null ?
                new ObjectParameter("emailEmpl", emailEmpl) :
                new ObjectParameter("emailEmpl", typeof(string));
    
            var fVencContEmplParameter = fVencContEmpl.HasValue ?
                new ObjectParameter("fVencContEmpl", fVencContEmpl) :
                new ObjectParameter("fVencContEmpl", typeof(System.DateTime));
    
            var sexoEmplParameter = sexoEmpl != null ?
                new ObjectParameter("sexoEmpl", sexoEmpl) :
                new ObjectParameter("sexoEmpl", typeof(string));
    
            var dniEmplParameter = dniEmpl != null ?
                new ObjectParameter("dniEmpl", dniEmpl) :
                new ObjectParameter("dniEmpl", typeof(string));
    
            var usuRegEmplParameter = usuRegEmpl != null ?
                new ObjectParameter("UsuRegEmpl", usuRegEmpl) :
                new ObjectParameter("UsuRegEmpl", typeof(string));
    
            var estEmplParameter = estEmpl != null ?
                new ObjectParameter("estEmpl", estEmpl) :
                new ObjectParameter("estEmpl", typeof(string));
    
            var aCFParameter = aCF != null ?
                new ObjectParameter("ACF", aCF) :
                new ObjectParameter("ACF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEmpleado", vcodEmplParameter, idUbigParameter, nombEmplParameter, apeEmplParameter, telfEmplParameter, emailEmplParameter, fVencContEmplParameter, sexoEmplParameter, dniEmplParameter, usuRegEmplParameter, estEmplParameter, aCFParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEmpleado_Result> usp_ConsultarEmpleado(string vcodEmpl)
        {
            var vcodEmplParameter = vcodEmpl != null ?
                new ObjectParameter("vcodEmpl", vcodEmpl) :
                new ObjectParameter("vcodEmpl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpleado_Result>("usp_ConsultarEmpleado", vcodEmplParameter);
        }
    
        public virtual int usp_EliminarEmpleado(string vcodEmpl)
        {
            var vcodEmplParameter = vcodEmpl != null ?
                new ObjectParameter("vcodEmpl", vcodEmpl) :
                new ObjectParameter("vcodEmpl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEmpleado", vcodEmplParameter);
        }
    
        public virtual int usp_InsertarEmpleado(string idUbig, string nombEmpl, string apeEmpl, Nullable<System.DateTime> fecIngrEmpl, string telfEmpl, string emailEmpl, Nullable<System.DateTime> fnacEmpl, Nullable<System.DateTime> fVencContEmpl, string sexoEmpl, string dniEmpl, string usuRegEmpl, string estEmpl, byte[] foto, string aCF)
        {
            var idUbigParameter = idUbig != null ?
                new ObjectParameter("idUbig", idUbig) :
                new ObjectParameter("idUbig", typeof(string));
    
            var nombEmplParameter = nombEmpl != null ?
                new ObjectParameter("NombEmpl", nombEmpl) :
                new ObjectParameter("NombEmpl", typeof(string));
    
            var apeEmplParameter = apeEmpl != null ?
                new ObjectParameter("ApeEmpl", apeEmpl) :
                new ObjectParameter("ApeEmpl", typeof(string));
    
            var fecIngrEmplParameter = fecIngrEmpl.HasValue ?
                new ObjectParameter("fecIngrEmpl", fecIngrEmpl) :
                new ObjectParameter("fecIngrEmpl", typeof(System.DateTime));
    
            var telfEmplParameter = telfEmpl != null ?
                new ObjectParameter("telfEmpl", telfEmpl) :
                new ObjectParameter("telfEmpl", typeof(string));
    
            var emailEmplParameter = emailEmpl != null ?
                new ObjectParameter("emailEmpl", emailEmpl) :
                new ObjectParameter("emailEmpl", typeof(string));
    
            var fnacEmplParameter = fnacEmpl.HasValue ?
                new ObjectParameter("fnacEmpl", fnacEmpl) :
                new ObjectParameter("fnacEmpl", typeof(System.DateTime));
    
            var fVencContEmplParameter = fVencContEmpl.HasValue ?
                new ObjectParameter("fVencContEmpl", fVencContEmpl) :
                new ObjectParameter("fVencContEmpl", typeof(System.DateTime));
    
            var sexoEmplParameter = sexoEmpl != null ?
                new ObjectParameter("sexoEmpl", sexoEmpl) :
                new ObjectParameter("sexoEmpl", typeof(string));
    
            var dniEmplParameter = dniEmpl != null ?
                new ObjectParameter("dniEmpl", dniEmpl) :
                new ObjectParameter("dniEmpl", typeof(string));
    
            var usuRegEmplParameter = usuRegEmpl != null ?
                new ObjectParameter("UsuRegEmpl", usuRegEmpl) :
                new ObjectParameter("UsuRegEmpl", typeof(string));
    
            var estEmplParameter = estEmpl != null ?
                new ObjectParameter("estEmpl", estEmpl) :
                new ObjectParameter("estEmpl", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var aCFParameter = aCF != null ?
                new ObjectParameter("ACF", aCF) :
                new ObjectParameter("ACF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEmpleado", idUbigParameter, nombEmplParameter, apeEmplParameter, fecIngrEmplParameter, telfEmplParameter, emailEmplParameter, fnacEmplParameter, fVencContEmplParameter, sexoEmplParameter, dniEmplParameter, usuRegEmplParameter, estEmplParameter, fotoParameter, aCFParameter);
        }
    
        public virtual ObjectResult<usp_ListarEmpleado_Result> usp_ListarEmpleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEmpleado_Result>("usp_ListarEmpleado");
        }
    }
}
