//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEmpleado
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Empleado
    {
        public string IDEmpleado { get; set; }
        public string IDUbigeo { get; set; }
        public string Nom_empl { get; set; }
        public string ape_empl { get; set; }
        public Nullable<System.DateTime> fecha_ingreso_empl { get; set; }
        public string telefono_empl { get; set; }
        public string correo_empl { get; set; }
        public Nullable<System.DateTime> fec_nacimiento_empl { get; set; }
        public Nullable<System.DateTime> fec_vencimi_contr_empl { get; set; }
        public string sexo_empl { get; set; }
        public string dni_empl { get; set; }
        public Nullable<System.DateTime> fec_reg_empl { get; set; }
        public string usu_reg_empl { get; set; }
        public Nullable<System.DateTime> fec_ultm_mod_empl { get; set; }
        public string usu_ultm_mod_empl { get; set; }
        public string estado_empl { get; set; }
        public byte[] Foto { get; set; }
        public string id_ACF { get; set; }
    }
}
