//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEmpleado
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Producto
    {
        public string IDProducto { get; set; }
        public string IDReceta { get; set; }
        public string IDUnidadMedida { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int presentacion { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Stock_min { get; set; }
        public Nullable<System.DateTime> fec_reg_pro { get; set; }
        public string usu_reg_pro { get; set; }
        public Nullable<System.DateTime> fec_ultm_mod_pro { get; set; }
        public string usu_ultm_mod_pro { get; set; }
        public string estado { get; set; }
    }
}
