//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEmpleado
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Proveedor
    {
        public string IDProveedor { get; set; }
        public string IDUbigeo { get; set; }
        public string nom_prv { get; set; }
        public string ape_prv { get; set; }
        public string telefono_prv { get; set; }
        public string correo_prv { get; set; }
        public string tipo_prv { get; set; }
        public string ruc_prv { get; set; }
        public Nullable<System.DateTime> fec_reg_prv { get; set; }
        public string usu_reg_prv { get; set; }
        public Nullable<System.DateTime> fec_ultm_mod_prv { get; set; }
        public string usu_ultm_mod_prv { get; set; }
        public string estado_prv { get; set; }
        public string raz_social_prv { get; set; }
    }
}
